### ISSUE TITLE
Quadratic runtime in tokenizer

### ISSUE THREAD

**Issue by NobbZ** [fabrik42/writing_an_interpreter_in_elixir#1]
Hi!

I took a first look into this project and started out with the tokenizer. It seems as if you are appending the last read token to the list of previously read tokens every time. This makes your code quadratic in runtime, since each append on itself is already linear.

To avoid this, there are some solutions possible which I will only draft out roughly here:

### Build the list forwards

```ex
def tokenize([h|t]), do: [decide_token(h)|tokenize(t)]
```

### Build the list backwards

```ex
def tokenize([], tokens), do: Enum.reverse(tokens)
def tokenize([h|t], tokens), do: tokenize(t, [decide_token(h)|tokens])
```

**Comment by fabrik42** [comment]
Hi,

thank you very much for pointing me in the right direction! I will go through the code and try to fix this. In the case of the `tokenize` function I would go for building the list backwards and then reversing it, because the function is called in many places and I can keep the calling of the function simpler this way.

But I will keep the way of building lists forward in mind, maybe there is a place where I can use it even better. :)

Best,

Christian

**Comment by fabrik42** [comment]
Just updated the code: https://github.com/fabrik42/writing_an_interpreter_in_elixir/commit/38a3af770fa4e564c94c794680ea89fe8d6ea9bf

**Comment by fabrik42** [comment]
I think I could also replace some recursions with higher order reduce functions like here: https://github.com/fabrik42/writing_an_interpreter_in_elixir/commit/77945858dae84e4e6ef4426dcedccd8383fb3beb
